### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by noraesae** [hachibasu/koko#1]
Basically, these are things to be done before releasing the first version.

- [x] Nick command & nick change handling
- [x] Unified shortcut system
- [x] `gt` and `gT` tap moving
- [x] VIM-like scrolling in NORMAL mode
- [x] window focus -> input focus(current)
- [x] Userlist
- [x] Intuitive InputBox styling for each mode
- [x] personal message
- [x] IRC log color & decoration handling
- [x] IRC log URL & image
- [x] Image scrolling
- [x] Paste doens't work
- [x] Youtube
- [x] Auto focus when connect channel
- [x] New simple command system.
- [x] Input scrollback
- [x] Nick autocomplete
- [x] Multi window
- [x] Mode
- [x] Whois
- [x] TypeScript
- [x] kick
- [x] ban / kickban / unban
- [x] Set topic
- [x] Topic view
- [x] Wrong scrollbar size with topic view when changing buffer
- [x] Channel mode print
- [x] New log text parsing method using React DOM directly.
- [x] Wrong topic URL with `"`
- [x] Highlight my nickname
- [x] Save LogContent per log object.
- [x] Fix whois to one log.
- [x] Better logo
- [x] Packaging
- [x] Insufficient information when connecting
- [x] Connect with configs: yml
- [x] Travis setting with release
- [x] User and contributor's manual as `.md` files.
- [x] Design update
- [x] Screenshots

The list can be modified anytime.

**Comment by noraesae** [comment]
Finished. Ready to move on!
